# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/form_text.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiDialogText(QtWidgets.QDialog):
    def __init__(self, text, title):
        super(UiDialogText, self).__init__()

        self.text = text
        self.title = title
        self._setupUi()

        self._set_data()

    def _setupUi(self):
        self.setObjectName("DialogText")
        self.resize(500, 200)
        self.setMinimumSize(QtCore.QSize(500, 200))
        self.setMaximumSize(QtCore.QSize(500, 200))
        self.setBaseSize(QtCore.QSize(500, 200))
        self.textEdit = QtWidgets.QTextEdit(self)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 500, 200))
        self.textEdit.setMinimumSize(QtCore.QSize(500, 200))
        self.textEdit.setMaximumSize(QtCore.QSize(500, 200))
        self.textEdit.setBaseSize(QtCore.QSize(500, 200))
        self.textEdit.setObjectName("textEdit")

        self._retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def _retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("DialogText", "Команда выполнения"))

    def _set_data(self):
        self.textEdit.setText(self.text)
        self.setWindowTitle(f"{self.title}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = UiDialogText("")
    ui.show()
    sys.exit(app.exec_())
